name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        password: ${{ secrets.DIGITALOCEAN_PASS }}
        port: ${{ secrets.DIGITALOCEAN_PORT }}
        script: |
          sh /var/respos/.deploy.sh
