name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Deploy DigitalOcean
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          password: ${{ secrets.DIGITALOCEAN_PASS }}
          port: ${{ secrets.DIGITALOCEAN_PORT }}
          script: |
            sh /var/repos/.deploy/api.sh
