name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to DigitalOcean
        run: |
          ssh-keyscan -H 162.243.166.100 >> ~/.ssh/known_hosts
          ssh 162.243.166.100 'sh /var/repos/.deploy/task.sh'
        env:
          NODE_ENV: production

