name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DIGITALOCEAN_USER }}
        username: ${{ secrets.DIGITALOCEAN_HOST }}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        command_timeout: 30m
        script: | 
          sh /var/repos/.deploy/task.sh
          

